Repository StenaIT/stenajs-webui, pull requests merged in 2022-06, with the labels that each got.

#459 Nav: Notification button + animation (fixes AB#92377)
  packages/elements/src/components/ui/buttons/PrimaryButton.tsx
  packages/elements/src/components/ui/buttons/common/ButtonCommon.ts
  packages/panels/src/components/nav-bar/NavBar.stories.tsx
  packages/panels/src/components/nav-bar/NavBarNotificationButton.module.css
  packages/panels/src/components/nav-bar/NavBarNotificationButton.tsx
  packages/panels/src/index.ts
Labels: enhancement

#460 Nav: New user icon (fixes AB#92613)
  packages/panels/src/components/action-menu-button/ActionMenuButton.tsx
  packages/panels/src/components/nav-bar/NavBar.stories.tsx
  packages/panels/src/components/nav-bar/NavBarUserButton.module.css
  packages/panels/src/components/nav-bar/NavBarUserButton.tsx
  packages/panels/src/index.ts
Labels: enhancement, minor

#462 Remove themes from CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip-release, documentation

#464 94903 add disabled state to date components
  packages/calendar/src/components/input-types/date-input/DateInput.stories.tsx
  packages/calendar/src/components/input-types/date-input/DateInput.tsx
  packages/calendar/src/components/input-types/date-range-dual-text-input/DateRangeDualTextInput.stories.tsx
  packages/calendar/src/components/input-types/date-range-dual-text-input/DateRangeDualTextInput.tsx
  packages/calendar/src/components/input-types/date-range-input/DateRangeInput.stories.tsx
  packages/calendar/src/components/input-types/date-range-input/DateRangeInput.tsx
  packages/calendar/src/components/input-types/date-time-input/DateTimeInput.stories.tsx
  packages/calendar/src/components/input-types/date-time-input/DateTimeInput.tsx
  packages/calendar/src/features/dual-text-input/DualTextInput.tsx
  packages/forms/src/components/ui/text-input/TextInput.module.css
Labels: enhancement, minor

#463 Add variant to Select and date inputs
  packages/calendar/src/components/input-types/date-range-dual-text-input/DateRangeDualTextInput.stories.tsx
  packages/calendar/src/components/input-types/date-range-dual-text-input/DateRangeDualTextInput.tsx
  packages/calendar/src/components/input-types/date-text-input/DateTextInput.stories.tsx
  packages/calendar/src/components/input-types/date-text-input/DateTextInput.tsx
  packages/calendar/src/components/input-types/date-time-input/DateTimeInput.stories.tsx
  packages/calendar/src/components/input-types/date-time-input/DateTimeInput.tsx
  packages/select/src/SelectTheme.ts
  packages/select/src/components/ui/AsyncMultiSelect.tsx
  packages/select/src/components/ui/AsyncSelect.stories.tsx
  packages/select/src/components/ui/AsyncSelect.tsx
  packages/select/src/components/ui/ChipMultiSelect/GroupedChipMultiSelect.stories.tsx
  packages/select/src/components/ui/GroupedMultiSelect.stories.tsx
  packages/select/src/components/ui/GroupedMultiSelect.tsx
  packages/select/src/components/ui/MultiSelect.stories.tsx
  packages/select/src/components/ui/MultiSelect.tsx
  packages/select/src/components/ui/Select.stories.tsx
  packages/select/src/components/ui/Select.tsx
  packages/select/src/index.ts
  packages/select/src/util/StylesBuilder.ts
  packages/select/src/util/StylesMerger.ts
  packages/theme/src/styles/default-theme.css
Labels: enhancement, major

#458 Accessible font-sizes using `rem` instead of `px`
  packages/core/src/components/heading/Heading.module.css
  packages/core/src/components/text/Text.module.css
  packages/elements/src/components/ui/bread-crumbs/Crumb.module.css
  packages/elements/src/components/ui/buttons/Button.module.css
  packages/elements/src/components/ui/chip/Chip.module.css
  packages/elements/src/components/ui/link/Link.module.css
  packages/elements/src/components/ui/tag/Tag.module.css
  packages/forms/src/components/ui/checkbox/Checkbox.module.css
  packages/forms/src/components/ui/radio/RadioButton.module.css
  packages/panels/src/components/collapsible/Collapsible.module.css
  packages/panels/src/components/nav-bar/NavBarSearchField.module.css
  packages/panels/src/components/sidebar-menu/SidebarMenuContent.module.css
  packages/theme/src/index.ts
  packages/theme/src/styles/base.css
  packages/theme/src/styles/default-theme.css
Labels: enhancement, minor

#466 Update Typescript, React, Jest, etc.
  jest.config.js
  package.json
  packages/calendar/package.json
  packages/calendar/src/components/calendar-types/single-week-calendar/UseSingleWeekSelection.ts
  packages/calendar/src/components/input-types/date-text-input/DateTextInput.tsx
  packages/calendar/src/components/input-types/time-text-input/TimeTextInput.tsx
  packages/calendar/src/declaration.d.ts
  packages/calendar/src/features/dual-text-input/DualTextInput.tsx
  packages/calendar/src/features/month-switcher/MonthSwitcherBelow.tsx
  packages/core/package.json
  packages/core/src/components/util/Nest.tsx
  packages/core/src/typings.d.ts
  packages/elements/package.json
  packages/elements/src/components/ui/action-menu/ActionMenu.stories.tsx
  packages/elements/src/components/ui/action-menu/ActionMenu.tsx
  packages/elements/src/components/ui/badge/WithBadge.tsx
  packages/elements/src/components/ui/banners/banner/Banner.tsx
  packages/elements/src/components/ui/bread-crumbs/BreadCrumbs.tsx
  packages/elements/src/components/ui/button-group/ButtonGroup.tsx
  packages/elements/src/components/ui/result-list/ResultList.tsx
  packages/elements/src/components/ui/tabs/TabMenu.tsx
  packages/elements/src/components/ui/value-table/ValueTable.tsx
  packages/elements/src/typings.d.ts
  packages/filter/package.json
  packages/filter/src/features/search-filter/features/chips/SearchFilterChips.tsx
  packages/filter/src/features/search-filter/section-factories/boolean-record/BooleanRecordChips.ts
  packages/filter/src/features/search-filter/section-factories/date-range/DateRangeChips.ts
  packages/filter/src/features/search-filter/section-factories/date-range/DateRangePropsFactory.ts
  packages/filter/src/typings.d.ts
  packages/forms/package.json
  packages/forms/src/components/ui/numeric-text-input/hooks/UseNumericInputValue.ts
  packages/forms/src/components/ui/text-input/TextInput.tsx
  packages/forms/src/components/ui/text-input/TextInputBox.tsx
  packages/forms/src/components/ui/text-input/__tests__/TextInput.test.tsx
  packages/grid-export/package.json
  packages/grid/package.json
  packages/grid/src/components/GridHooksTable.tsx
  packages/grid/src/typings.d.ts
  packages/input-mask/package.json
  packages/modal/package.json
  packages/modal/src/components/modal/ModalFooter.tsx
  packages/panels/package.json
  packages/panels/src/components/nav-bar/NavBar.tsx
  packages/panels/src/components/page-header/PageHeader.tsx
  packages/panels/src/components/sidebar-menu/SidebarMenuCollapsible.tsx
  packages/panels/src/components/sidebar-menu/rail/SidebarRailMenu.tsx
  packages/panels/src/typings.d.ts
  packages/redux/package.json
  packages/select/package.json
  packages/theme/package.json
  packages/theme/src/typings.d.ts
  packages/tooltip/package.json
  setupTests.js
  template/package.json
  yarn.lock
Labels: dependencies

#468 Fix key and activeClassName-warnings
  packages/panels/src/components/sidebar-menu/SidebarMenuLink.tsx
  packages/panels/src/components/sidebar-menu/rail/renderer/RailRenderer.tsx
Labels: bug, patch

#469 Fix misaligned StandardTable header when rowCheckbox is true and headerCheckbox is false
  packages/grid/src/features/standard-table/components/StandardTableHeadRow.tsx
  packages/grid/src/features/standard-table/stories/StandardTable.stories.tsx
Labels: bug, patch

#470 Change color of blue-600 to match with "Hav"
  packages/theme/src/styles/default-colors.css
Labels: enhancement, minor

#457 Add SelectedItemsActionsPanel component
  packages/panels/src/components/selected-items-actions-panel/SelectedItemsActionsPanel.stories.tsx
  packages/panels/src/components/selected-items-actions-panel/SelectedItemsActionsPanel.tsx
  packages/panels/src/index.ts
Labels: enhancement, minor

#472 `SearchFilterDrawer` pass `header` prop down to `SearchFilterPanelHeader`
  packages/filter/src/features/search-filter/components/SearchFilterDrawer.tsx
Labels: bug, patch
