Repository StenaIT/stenajs-webui, pull requests merged in 2022-11, with the labels that each got.

#526 Add more webui icons
  packages/elements/src/icons/ui/IconsUi.ts
Labels: minor

#527 Modal is fullscreen on mobile
  packages/modal/src/components/modal/Modal.module.css
  packages/modal/src/components/modal/Modal.stories.tsx
Labels: enhancement, minor

#529 Change form field default colors (AB#102893)
  packages/theme/src/styles/default-theme.css
Labels: minor

#531 Fix variable used before declaration error
  packages/calendar/src/components/input-types/date-range-input/DateRangeInput.tsx
Labels: bug, patch, documentation
