Repository StenaIT/stenajs-webui, pull requests merged in 2022-08, with the labels that each got.

#484 Fix keyboard navigation in StandardTable
  packages/grid/src/features/grid-cell/hooks/UseGridNavigation.ts
Labels: bug, patch

#485 Do not render space below heading if PageHeader has no breadcrumbs
  packages/panels/src/components/page-header/PageHeader.stories.tsx
  packages/panels/src/components/page-header/PageHeader.tsx
Labels: enhancement, minor

#487 Add change icon label functionality
  packages/filter/src/features/search-filter/components/SearchFilterButton.tsx
  packages/filter/src/features/search-filter/components/SearchFilterDrawer.tsx
  packages/filter/src/features/search-filter/components/SearchFilterPanelHeader.tsx
Labels: enhancement, minor

#488 Bring back lost font family to Select group heading
  packages/select/src/util/StylesBuilder.ts
Labels: bug, patch

#492 New batch of Stena SVG icons
  packages/elements/src/icons/misc/IconsMisc.stories.tsx
  packages/elements/src/icons/ui/IconsUi.stories.tsx
  packages/elements/src/icons/ui/IconsUi.ts
  packages/elements/src/icons/ui/IconsUiDemo.tsx
Labels: minor, skip-release

#493 Switch and minus replacements
  packages/elements/src/icons/ui/IconsUi.ts
Labels: skip-release

#494 Only use cssInjectedByJsPlugin in production
  .storybook/main.js
Labels: skip-release

#496 Fix extractCss config in production
  .storybook/main.js
Labels: skip-release

#490 Add route leg component
  packages/elements/src/components/ui/route-leg/RouteLeg.module.css
  packages/elements/src/components/ui/route-leg/RouteLeg.stories.tsx
  packages/elements/src/components/ui/route-leg/RouteLeg.tsx
  packages/elements/src/components/ui/route-leg/TimeTag.module.css
  packages/elements/src/components/ui/route-leg/TimeTag.tsx
  packages/elements/src/icons/ui/IconsUi.ts
  packages/elements/src/index.ts
Labels: enhancement, minor

#497 Align table head left
  packages/grid/src/features/table-ui/components/table/TableHeadItem.tsx
Labels: patch

#502 Upgrade storybook, vite and ts
  .storybook/main.ts
  .storybook/manager.ts
  .storybook/preview.ts
  package.json
  packages/calendar/src/components/calendar-types/date-range-calendar/DateRangeCalendar.tsx
  packages/calendar/src/components/calendar-types/date-range-exclusion-calendar/DateRangeExclusionCalendar.tsx
  packages/calendar/src/components/calendar-types/multi-date-calendar/MultiDateCalendar.tsx
  packages/calendar/src/components/calendar-types/single-date-calendar/SingleDateCalendar.tsx
  packages/calendar/src/components/calendar/Calendar.tsx
  packages/calendar/src/components/calendar/CalendarTheme.tsx
  packages/calendar/src/components/calendar/renderers/CalendarDay.tsx
  packages/calendar/src/components/input-types/date-range-dual-text-input/DateRangeDualTextInput.tsx
  packages/calendar/src/components/input-types/date-range-input/DateRangeInput.tsx
  packages/filter/src/features/search-filter/section-factories/date-range/DateRangeChips.ts
  packages/select/src/components/ui/AsyncMultiSelect.tsx
  packages/select/src/components/ui/AsyncSelect.tsx
  packages/select/src/components/ui/GroupedMultiSelect.tsx
  packages/select/src/components/ui/MultiSelect.tsx
  packages/select/src/components/ui/Select.tsx
  tsconfig.json
  yarn.lock
Labels: dependencies, skip-release, internal

#499 Remove link styling for last-of-type (fixes AB#97856)
  packages/elements/src/components/ui/bread-crumbs/Crumb.module.css
Labels: enhancement, skip-release

#501 Fix stenaSailingRoute icon
  packages/elements/src/icons/ui/IconsUi.ts
Labels: bug, patch
