Repository StenaIT/stenajs-webui, pull requests merged in 2022-02, with the labels that each got.

#431 Fix missing peer dependencies
  .github/workflows/nodejs.yml
  .github/workflows/release.yml
  package.json
  packages/core/package.json
  packages/filter/package.json
  packages/grid/package.json
  packages/tooltip/package.json
  yarn.lock
Labels: dependencies, skip-release

#432 Re-add git fetch --tags which is needed by auto
  .github/workflows/nodejs.yml
Labels: skip-release

#434 Use stena sans cloudfront font CDN
  .storybook/preview-head.html
  FONTS.md
  README.md
Labels: skip-release, internal, documentation

#433 Fix select typings and styling regression
  packages/select/src/components/ui/GroupedMultiSelect.tsx
  packages/select/src/util/__tests__/multiDropdownUtils.test.ts
  packages/select/src/util/multiDropdownUtils.ts
Labels: bug, patch

#435 Increase contrast of Heading.
  packages/core/src/components/heading/Heading.module.css
Labels: enhancement, skip-release

#436 Some design updates on search filter drawer and panel
  packages/filter/src/features/search-filter/components/SearchFilterDrawer.tsx
  packages/filter/src/features/search-filter/components/SearchFilterPanelHeader.tsx
Labels: enhancement, skip-release

#437 Support initial state in reducer factories
  packages/grid/src/features/standard-table/redux/StandardTableReducer.ts
  packages/redux/src/features/reducer-factories/selected-ids-reducer/selected-ids-reducer.ts
  packages/redux/src/features/reducer-factories/sort-order-reducer/sort-order-reducer.ts
Labels: minor, internal

#284 Change bold font weight to 500
  packages/elements/src/components/ui/bread-crumbs/Crumb.module.css
  packages/panels/src/components/collapsible/Collapsible.module.css
  packages/panels/src/components/collapsible/Collapsible.tsx
  packages/theme/src/styles/default-theme.css
Labels: enhancement, minor
