Repository StenaIT/stenajs-webui, pull requests merged in 2022-12, with the labels that each got.

#541 Add support for locale in calendar
  packages/calendar/src/components/calendar-types/date-range-calendar/DateRangeCalendar.stories.tsx
  packages/calendar/src/components/calendar-types/single-week-calendar/UseSingleWeekSelection.ts
  packages/calendar/src/components/calendar/Calendar.tsx
  packages/calendar/src/components/calendar/CalendarMonth.tsx
  packages/calendar/src/types/CalendarTypes.tsx
  packages/calendar/src/util/calendar/CalendarDataFactory.ts
  packages/calendar/src/util/calendar/__tests__/CalendarDataFactory.test.ts
Labels: enhancement, minor

#534 Remove children from ActionMenuItem (fixes AB#104119)
  packages/elements/src/components/ui/action-menu/ActionMenuItem.tsx
Labels: bug, patch

#542 Update and add new icons
  packages/elements/src/icons/ui/IconsUi.ts
Labels: minor
