Repository StenaIT/stenajs-webui, pull requests merged in 2022-03, with the labels that each got.

#438 Disable calendar widget for https://stenait.github.io/stenajs-webui/?path=/story/calendar-input-datetextinput--disabled (fixes AB#86042)
  packages/calendar/src/components/input-types/date-text-input/DateTextInput.tsx
Labels: bug, patch

#439 Update font color and line height (fixes AB#87047)
  packages/core/src/components/heading/Heading.module.css
  packages/core/src/components/text/Text.module.css
  packages/theme/src/styles/default-theme.css
Labels: enhancement, minor

#443 Update Card header (fixes AB#88134)
  packages/elements/src/components/ui/cards/Card.stories.tsx
  packages/elements/src/components/ui/cards/CardBody.tsx
  packages/elements/src/components/ui/cards/CardHeader.module.css
  packages/elements/src/components/ui/cards/CardHeader.tsx
Labels: patch, skip-release

#444 Render only one March month
  packages/calendar/src/features/month-picker/MonthPickerCell.tsx
Labels: bug, patch

#440 Wrong number of tds in summary row in StandardTable
  packages/grid/src/features/standard-table/features/summary-row/components/StandardTableSummaryRow.module.css
  packages/grid/src/features/standard-table/features/summary-row/components/StandardTableSummaryRow.tsx
Labels: bug, patch
