Repository StenaIT/stenajs-webui, pull requests merged in 2022-10, with the labels that each got.

#514 Update icon library
  packages/elements/src/icons/ui/IconsUi.ts
Labels: minor

#515 Use kebab-case in the Icons story for better readability
  packages/elements/src/icons/ui/IconsUi.stories.tsx
Labels: skip-release

#517 Use Stena icon in "Clear all" button in SelectedItemsActionsPanel
  packages/panels/src/components/selected-items-actions-panel/SelectedItemsActionsPanel.stories.tsx
Labels: minor

#518 Increase contrast in FlatButton colors
  packages/elements/src/components/ui/buttons/FlatButton.module.css
Labels: enhancement, minor

#521 Add `StickyFooter` for filter, automatically makes buttons 100% wide
  packages/filter/src/features/search-filter/components/ClearFiltersButton.tsx
  packages/filter/src/features/search-filter/components/StickyFooter.tsx
  packages/filter/src/features/search-filter/stories/SearchFilter.stories.tsx
  packages/filter/src/index.ts
Labels: enhancement, minor

#520 Use circle icon for nav bar user button
  packages/panels/src/components/nav-bar/NavBarUserButton.tsx
Labels: enhancement, minor

#519 Last crumb in bread crumbs has the same color as the rest
  packages/elements/src/components/ui/bread-crumbs/Crumb.module.css
Labels: bug, patch

#522 Add `CopyToClipboardButton` which can copy specified text to clipboard
  packages/forms/package.json
  packages/forms/src/components/copy-to-clipboard-button/CopyToClipboardButton.stories.tsx
  packages/forms/src/components/copy-to-clipboard-button/CopyToClipboardButton.tsx
Labels: enhancement, minor
