Repository StenaIT/stenajs-webui, pull requests merged in 2022-04, with the labels that each got.

#441 Added property hideBorderTop to TableRow
  packages/grid/src/config/TableConfig.ts
  packages/grid/src/features/table-ui/components/table/TableRow.tsx
  packages/grid/src/features/table-ui/stories/TableUi.stories.tsx
Labels: enhancement, minor

#448 Fix tabmenu colors (fixes AB#91051)
  packages/elements/src/components/ui/tabs/Tab.module.css
  packages/elements/src/components/ui/tabs/Tab.tsx
  packages/elements/src/components/ui/tabs/TabMenu.module.css
  packages/elements/src/components/ui/tabs/TabMenu.tsx
Labels: patch, skip-release

#449 Pass itemKey to renderProps in StandardTable
  packages/grid/src/features/standard-table/components/StandardTableCell.tsx
  packages/grid/src/features/standard-table/config/StandardTableColumnConfig.ts
Labels: patch

#450 Fix event propagation bug in onKeyDown in StandardTable
  packages/grid/src/features/standard-table/components/StandardTableCell.tsx
  packages/grid/src/features/standard-table/stories/StandardTable.stories.tsx
Labels: bug, patch

#451 Remove storybook deploy scripts
  package.json
  yarn.lock
Labels: skip-release

#452 Improve spacing in PageHeader when there are no tabs
  packages/panels/src/components/page-header/PageHeader.stories.tsx
  packages/panels/src/components/page-header/PageHeader.tsx
  packages/panels/src/components/page-header/PageHeaderRow.tsx
  packages/panels/src/components/page-header/PageHeading.tsx
  packages/panels/src/index.ts
Labels: bug, patch

#453 Add compact variant to cardbody
  packages/elements/src/components/ui/cards/Card.stories.tsx
  packages/elements/src/components/ui/cards/CardBody.tsx
Labels: enhancement
