Repository StenaIT/stenajs-webui, pull requests merged in 2023-03, with the labels that each got.

#564 Tooling: Upgrade lerna to latest version
  lerna.json
  package.json
  yarn.lock
Labels: skip-release, internal

#567 Add several finance icons (AB#109066)
  packages/elements/src/icons/ui/IconsUi.ts
Labels: minor, skip-release

#565 New design for `Tag`
  packages/elements/src/components/ui/tag/Tag.module.css
  packages/elements/src/components/ui/tag/Tag.stories.tsx
  packages/elements/src/components/ui/tag/Tag.tsx
Labels: enhancement, minor

#568 Tag icon size is different depending on variant
  packages/elements/src/components/ui/tag/Tag.module.css
  packages/elements/src/components/ui/tag/Tag.stories.tsx
  packages/elements/src/components/ui/tag/Tag.tsx
Labels: enhancement, minor

#569 Small fix for Tag icon when using global border-box
  packages/elements/src/components/ui/tag/Tag.module.css
Labels: bug, patch
