Repository StenaIT/stenajs-webui, pull requests merged in 2023-02, with the labels that each got.

#554 External sorting and `onSortOrderChange` prop in StandardTable
  packages/grid/src/features/standard-table/components/StandardTable.tsx
  packages/grid/src/features/standard-table/components/StandardTableRowList.tsx
  packages/grid/src/features/standard-table/config/StandardTableConfig.ts
  packages/grid/src/features/standard-table/context/OnKeyDownContext.ts
  packages/grid/src/features/standard-table/context/OnSortOrderChangeContext.ts
  packages/grid/src/features/standard-table/features/sorting/UseTableSortHeader.ts
  packages/grid/src/features/standard-table/stories/StandardTable.stories.tsx
  packages/grid/src/features/standard-table/types/StandardTableEvents.ts
  packages/grid/src/index.ts
Labels: enhancement, minor, skip-release

#555 Now possible to style button with only icon to have custom sizes
  packages/elements/src/components/ui/buttons/Button.module.css
Labels: enhancement, minor

#557 ResultListBanner can have children, shown below bulletpoint list
  packages/elements/src/components/ui/banners/result-list-banner/ResultListBanner.tsx
Labels: enhancement, minor

#558 Add file icons with labels and finance paid status icons
  packages/elements/src/icons/ui/IconsUi.ts
Labels: minor

#559 Update icons in banner
  packages/elements/src/components/ui/banners/banner/Banner.module.css
  packages/elements/src/components/ui/banners/banner/Banner.tsx
Labels: enhancement, minor

#533 Change focus to focus-visible for form elements
  packages/elements/src/components/ui/buttons/Button.module.css
  packages/elements/src/components/ui/up-down-buttons/UpDownButtons.module.css
  packages/forms/src/components/ui/checkbox/Checkbox.module.css
  packages/forms/src/components/ui/radio/RadioButton.module.css
  packages/forms/src/components/ui/switch/Switch.module.css
Labels: enhancement, patch, skip-release

#556 changing color for disabled UI elements
  packages/elements/src/components/ui/buttons/Button.module.css
  packages/elements/src/components/ui/buttons/SecondaryButton.module.css
  packages/forms/src/components/ui/checkbox/Checkbox.module.css
  packages/forms/src/components/ui/radio/RadioButton.module.css
  packages/select/src/SelectTheme.ts
  packages/select/src/util/StylesBuilder.ts
  packages/theme/src/styles/default-theme.css
Labels: minor, skip-release

#530 Actually disable the calendar icon button in DateTextInput
  packages/calendar/src/components/input-types/date-text-input/DateTextInput.tsx
Labels: bug, patch, skip-release

#549 Add Toast and remake Notification
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  packages/panels/src/components/notifications/Notification.stories.tsx
  packages/panels/src/components/notifications/Notification.tsx
  packages/panels/src/components/notifications/NotificationHeader.tsx
  packages/panels/src/components/notifications/NotificationTheme.ts
  packages/panels/src/components/notifications/Toast.module.css
  packages/panels/src/components/notifications/Toast.stories.tsx
  packages/panels/src/components/notifications/Toast.tsx
  packages/panels/src/index.ts
  packages/panels/src/storybook-helpers/storybook-controls.ts
  yarn.lock
Labels: enhancement, major

#562 Make `Heading` style customisable
  packages/core/src/components/heading/Heading.module.css
Labels: enhancement, patch

#503 Use NavBarSearchField in center content story
  packages/panels/src/components/nav-bar/NavBar.stories.tsx
Labels: skip-release, documentation

#561 Add headingLevel to PageHeading, default being h1
  packages/panels/src/components/page-header/PageHeader.stories.tsx
  packages/panels/src/components/page-header/PageHeading.tsx
Labels: bug, patch

#537 Rewrite tooltip using TippyComponent instead of Popover
  packages/tooltip/package.json
  packages/tooltip/src/components/popover/Popover.tsx
  packages/tooltip/src/components/popover/Tippy.module.css
  packages/tooltip/src/components/tooltip/Tooltip.module.css
  packages/tooltip/src/components/tooltip/Tooltip.stories.tsx
  packages/tooltip/src/components/tooltip/Tooltip.tsx
Labels: enhancement, minor

#563 Button icons now customisable using CSS properties
  packages/elements/src/components/ui/button-links/PrimaryButtonLink.tsx
  packages/elements/src/components/ui/buttons/Button.module.css
  packages/elements/src/components/ui/buttons/PrimaryButton.tsx
  packages/elements/src/components/ui/buttons/common/ButtonCommon.ts
  packages/elements/src/components/ui/buttons/common/ButtonContent.module.css
  packages/elements/src/components/ui/buttons/common/ButtonContent.tsx
  packages/elements/src/components/ui/icon/Icon.tsx
Labels: bug, patch

#560 New modal API
  packages/elements/src/components/ui/dialog/DialogCommands.ts
  packages/elements/src/components/ui/dialog/DialogContext.ts
  packages/elements/src/components/ui/dialog/UseDialog.tsx
  packages/elements/src/components/ui/dialog/UseDialogPromise.ts
  packages/elements/src/components/ui/dialog/drawer/DrawerDialog.module.css
  packages/elements/src/components/ui/dialog/drawer/UseDrawerDialog.ts
  packages/elements/src/components/ui/dialog/modal/ModalDialog.module.css
  packages/elements/src/components/ui/dialog/modal/UseModalDialog.ts
  packages/elements/src/components/ui/dialog/stories/DrawerDialog.stories.tsx
  packages/elements/src/components/ui/dialog/stories/ModalDialog.stories.tsx
  packages/elements/src/index.ts
Labels: enhancement, minor
