Repository StenaIT/stenajs-webui, pull requests merged in 2023-10, with the labels that each got.

#614 Bump lerna to 7
  .github/workflows/nodejs.yml
  CONTRIBUTING.md
  lerna.json
  package.json
  yarn.lock
Labels: skip-release, internal

#581 Bump storybook and related dependencies
  .storybook/main.ts
  package.json
  yarn.lock
Labels: skip-release, documentation

#617 Sticky header in SidebarMenu
  packages/panels/src/components/nav-bar/NavBar.stories.tsx
  packages/panels/src/components/sidebar-menu/SidebarMenu.tsx
  packages/panels/src/components/sidebar-menu/SidebarMenuCloseButtonRow.tsx
Labels: skip-release

#647 New component: LabelledTextInput
  packages/forms/package.json
  packages/forms/src/components/ui/input-label/InputLabel.tsx
  packages/forms/src/components/ui/input-label/InputLabelText.tsx
  packages/forms/src/components/ui/labelled-text-input/LabelledTextInput.module.css
  packages/forms/src/components/ui/labelled-text-input/LabelledTextInput.stories.tsx
  packages/forms/src/components/ui/labelled-text-input/LabelledTextInput.tsx
  packages/forms/src/index.ts
  packages/theme/src/styles/default-theme.css
Labels: skip-release

#648 Arrow icon fix
  packages/elements/src/icons/generated/ArrowIcons.ts
  scripts/icons/arrow-icons/arrow-double-vertical.svg
Labels: skip-release
