Repository StenaIT/stenajs-webui, pull requests merged in 2023-09, with the labels that each got.

#580 Column group header in standard table is transparent instead of filled
  packages/grid/src/features/standard-table/features/column-groups/ColumnGroupRow.tsx
Labels: bug, patch

#578 Add new ShimmerBox component
  packages/elements/src/components/ui/shimmer-box/ShimmerBox.module.css
  packages/elements/src/components/ui/shimmer-box/ShimmerBox.stories.tsx
  packages/elements/src/components/ui/shimmer-box/ShimmerBox.tsx
  packages/elements/src/index.ts
Labels: enhancement, minor

#585 Add checkboxDisabled prop to CollapsibleWithCheckbox
  packages/panels/src/components/collapsible/CollapsibleWithCheckbox.tsx
Labels: enhancement, minor

#586 Fixed issue with new disabled functionality in CollapsibleWithCheckbox
  packages/panels/src/components/collapsible/CollapsibleWithCheckbox.tsx
Labels: enhancement, patch

#587 Fixed issue with always requiring checkboxDisabled in CollapsibleWithCheckbox.
  packages/panels/src/components/collapsible/CollapsibleWithCheckbox.tsx
Labels: bug, patch

#545 Add filled versions of some icons
  packages/elements/src/icons/ui/IconsUi.ts
Labels: enhancement, minor

#593 Update banner default height (spacing = 1)
  packages/elements/src/components/ui/banners/banner/Banner.module.css
  packages/elements/src/components/ui/banners/banner/Banner.stories.tsx
  packages/elements/src/components/ui/banners/banner/Banner.tsx
Labels: patch

#597 New component: Cardy
  packages/elements/src/components/ui/card/Card.stories.tsx
  packages/elements/src/components/ui/card/Card.tsx
  packages/elements/src/components/ui/card/CardBody.tsx
  packages/elements/src/components/ui/card/CardHeader.tsx
  packages/elements/src/components/ui/cardy/Cardy.module.css
  packages/elements/src/components/ui/cardy/Cardy.stories.tsx
  packages/elements/src/components/ui/cardy/Cardy.tsx
  packages/elements/src/components/ui/cardy/CardyBody.tsx
  packages/elements/src/components/ui/cardy/CardyHeader.tsx
  packages/elements/src/index.ts
  packages/theme/src/styles/default-theme.css
Labels: enhancement, minor

#601 Fix color prop in Cardy.
  packages/elements/src/components/ui/cardy/Cardy.tsx
Labels: bug, patch

#573 Set line-height to 1.5
  packages/core/src/components/heading/Heading.module.css
  packages/theme/src/styles/default-theme.css
  packages/tooltip/src/components/popover/Tippy.module.css
Labels: enhancement, minor

#604 Some redesign fixes
  packages/core/src/components/heading/Heading.module.css
  packages/core/src/components/heading/Heading.stories.tsx
  packages/elements/src/components/ui/action-menu/ActionMenu.stories.tsx
  packages/elements/src/components/ui/action-menu/ActionMenuItemContent.tsx
  packages/elements/src/components/ui/buttons/menu-button/MenuButtonLink.tsx
  packages/elements/src/components/ui/chip/Chip.module.css
  packages/panels/src/components/checkbox-menu/CheckboxMenu.tsx
  packages/panels/src/components/nav-bar/NavBar.stories.tsx
  packages/panels/src/components/nav-bar/NavBarNotificationButton.module.css
  packages/panels/src/components/nav-bar/NavBarNotificationButton.tsx
  packages/panels/src/components/notifications/Notification.stories.tsx
  packages/panels/src/components/notifications/Notification.tsx
Labels: major
