Repository StenaIT/stenajs-webui, pull requests merged in 2023-05, with the labels that each got.

#576 Add initialDateInFocus prop to DateRangeCalendar
  packages/calendar/src/components/calendar-types/date-range-calendar/DateRangeCalendar.tsx
  packages/calendar/src/components/calendar-types/date-range-calendar/hooks/UseDateRangeSelection.ts
Labels: enhancement, minor

#577 StandardTable header can now expand when label is large or long
  packages/grid/src/features/standard-table/components/StandardTableHeadItem.tsx
Labels: bug, patch

#575 Add labelClassName and gap instead of Space
  packages/elements/src/components/ui/label/Label.tsx
Labels: patch

#574 Update design and functionality of ToggleButton
  packages/elements/src/components/ui/button-group/ButtonGroup.module.css
  packages/elements/src/components/ui/toggle-button/ToggleButton.module.css
  packages/elements/src/components/ui/toggle-button/ToggleButton.stories.tsx
  packages/elements/src/components/ui/toggle-button/ToggleButton.tsx
Labels: minor
