Repository StenaIT/stenajs-webui, pull requests merged in 2023-11, with the labels that each got.

#655 Move Button in ActionMenuButton outside of Popover
  packages/panels/src/components/action-menu-button/ActionMenuButton.stories.tsx
  packages/panels/src/components/action-menu-button/ActionMenuButton.tsx
  packages/tooltip/src/components/popover/Popover.tsx
Labels: skip-release

#671 Fix SidebarMenu CloseButton being wrong color
  packages/panels/src/components/sidebar-menu/SidebarMenu.module.css
  packages/panels/src/components/sidebar-menu/SidebarMenu.tsx
Labels: bug, skip-release

#670 Add ref and spin props to TextInputButton
  packages/forms/src/components/ui/text-input/TextInputButton.tsx
Labels: enhancement, skip-release

#669 Adjust NotificationButton background color
  packages/panels/src/components/nav-bar/NavBarNotificationButton.module.css
Labels: bug, skip-release

#668 Fix broken NavBarButton styles
  packages/panels/src/components/nav-bar/NavBarButton.module.css
  packages/panels/src/components/nav-bar/NavBarUserButton.module.css
Labels: bug, patch

#682 Remove extra padding at the bottom of Cardy
  packages/elements/src/components/ui/cardy/Cardy.module.css
Labels: skip-release

#683 Update design of ErrorPanel
  packages/elements/src/components/ui/icon/CircledIcon.stories.tsx
  packages/elements/src/components/ui/icon/CircledIcon.tsx
  packages/elements/src/icons/Icons.stories.tsx
  packages/elements/src/icons/IconsDemo.tsx
  packages/elements/src/icons/generated/BusinessIcons.ts
  packages/elements/src/icons/generated/CommonIcons.ts
  packages/elements/src/icons/generated/XlIcons.ts
  packages/elements/src/index.ts
  packages/panels/src/components/error-panel/ErrorPanel.stories.tsx
  packages/panels/src/components/error-panel/ErrorPanel.tsx
  packages/panels/src/components/error-panel/ErrorScreen.stories.tsx
  scripts/icons/business-icons/business-card.svg
  scripts/icons/business-icons/finance-paid.svg
  scripts/icons/business-icons/finance-pay-partially.svg
  scripts/icons/business-icons/finance-pay.svg
  scripts/icons/business-icons/finance-unpaid.svg
  scripts/icons/common-icons/lighthouse-xl.svg
  scripts/icons/common-icons/service.svg
  scripts/icons/xl-icons/lighthouse-xl.svg
  scripts/icons/xl-icons/trip-ferry-xl.svg
Labels: skip-release
