Repository StenaIT/stenajs-webui, pull requests merged in 2024-10, with the labels that each got.

#789 Add appendTo and zIndex props to DateTimeInput
  packages/calendar/src/components/input-types/date-time-input/DateTimeInput.tsx
  packages/tooltip/src/components/popover/ControlledPopover.tsx
  packages/tooltip/src/components/popover/Popover.tsx
Labels: enhancement, minor

#791 Prevent row breaks in label of LabelledTextInput and LabelledSelect
  packages/forms/src/components/ui/input-label/InputLabelText.tsx
  packages/forms/src/components/ui/labelled-text-input/LabelledTextInput.stories.tsx
Labels: bug, patch

#792 Upgrade lots of deps
  eslint.config.js
  package.json
  packages/calendar/src/components/input-types/date-range-input/hooks/UseDateRangeInput.tsx
  packages/calendar/src/util/time/TimeTransformer.ts
  packages/core/src/utils/parsers/NumberParser.ts
  packages/modal/src/dialog/alert/AlertDialog.stories.tsx
  packages/modal/src/dialog/modal/ModalDialog.stories.tsx
  yarn.lock
Labels: dependencies, minor

#793 Update to latest Storybook
  .github/workflows/nodejs.yml
  .nvmrc
  .storybook/main.ts
  package.json
  packages/forms/src/components/ui/numeric-text-input/NumericTextInput.tsx
  scripts/check-imports.cjs
  yarn.lock
Labels: patch, documentation

#790 Apply security best practices
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/scorecards.yml
  README.md
Labels: skip-release

#849 Update and clear out unused deps
  .storybook/main.ts
  package.json
  packages/calendar/package.json
  packages/core/package.json
  packages/elements/package.json
  packages/filter/package.json
  packages/forms/package.json
  packages/grid-export/package.json
  packages/grid/package.json
  packages/input-mask/package.json
  packages/modal/package.json
  packages/panels/package.json
  packages/redux/package.json
  packages/select/package.json
  packages/theme/package.json
  packages/tooltip/package.json
  template/package.json
  yarn.lock
Labels: dependencies, minor

#851 Update redux to latest version
  packages/filter/package.json
  packages/grid/package.json
  packages/grid/src/features/table-ui/components/cells/EditableTextCellWithCrudAndModified.tsx
  packages/redux/package.json
  yarn.lock
Labels: dependencies, minor

#853 Update clipboard-polyfill.
  packages/grid-export/package.json
  yarn.lock
Labels: dependencies, patch

#865 Upgrade Storybook to 8.3.6
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  packages/calendar/package.json
  packages/elements/package.json
  packages/filter/package.json
  packages/forms/package.json
  packages/grid-export/package.json
  packages/grid/package.json
  packages/input-mask/package.json
  packages/modal/package.json
  packages/panels/package.json
  packages/redux/package.json
  packages/select/package.json
  packages/theme/package.json
  packages/tooltip/package.json
  template/package.json
  yarn.lock
Labels: skip-release, documentation

#868 Fix MonthPicker having wrong locale
  packages/calendar/src/components/calendar-types/travel-date-calendar/TravelDateCalendar.tsx
  packages/calendar/src/components/calendar-types/travel-date-range-calendar/TravelDateRangeCalendar.tsx
  packages/calendar/src/components/input-types/date-input/DateInput.stories.tsx
  packages/calendar/src/components/input-types/date-input/DateInput.tsx
  packages/calendar/src/components/input-types/date-range-dual-text-input/DateRangeDualTextInput.stories.tsx
  packages/calendar/src/components/input-types/date-range-input/DateRangeInput.stories.tsx
  packages/calendar/src/components/input-types/date-range-input/DateRangeInput.tsx
  packages/calendar/src/components/input-types/date-text-input/DateTextInput.stories.tsx
  packages/calendar/src/components/input-types/date-text-input/DateTextInput.tsx
  packages/calendar/src/components/input-types/date-time-input/DateTimeInput.stories.tsx
  packages/calendar/src/components/input-types/travel-date-input/TravelDateInput.tsx
  packages/calendar/src/components/input-types/travel-date-range-input/TravelDateRangeInput.tsx
  packages/calendar/src/features/calendar-with-month-year-pickers/CalendarWithMonthYearPickers.tsx
  packages/calendar/src/features/localize-date-format/LocaleMapper.ts
  packages/calendar/src/features/month-picker/MonthPicker.stories.tsx
  packages/calendar/src/features/month-picker/MonthPicker.tsx
  packages/calendar/src/features/month-picker/MonthPickerCell.tsx
  packages/calendar/src/features/year-picker/YearPicker.stories.tsx
Labels: bug, minor

#870 Locale mapping falls back to language match only
  packages/calendar/src/features/localize-date-format/LocaleMapper.ts
  packages/calendar/src/features/localize-date-format/__tests__/LocaleMapper.test.ts
Labels: enhancement, minor

#871 Improve type and run-time safety for locale codes
  packages/calendar/src/components/calendar-types/travel-date-calendar/TravelDateCalendar.tsx
  packages/calendar/src/components/calendar-types/travel-date-range-calendar/TravelDateRangeCalendar.tsx
  packages/calendar/src/components/input-types/travel-date-input/TravelDateInput.tsx
  packages/calendar/src/components/input-types/travel-date-range-input/TravelDateRangeInput.tsx
  packages/calendar/src/features/calendar-with-month-year-pickers/CalendarWithMonthYearPickers.tsx
  packages/calendar/src/features/localize-date-format/DateFormatProvider.ts
  packages/calendar/src/features/localize-date-format/LocaleMapper.ts
  packages/calendar/src/features/localize-date-format/LocalizedDateFormatter.ts
  packages/calendar/src/features/localize-date-format/LocalizedDateParser.ts
  packages/calendar/src/features/localize-date-format/__tests__/LocaleMapper.test.ts
  packages/calendar/src/features/month-picker/MonthPicker.tsx
  packages/calendar/src/features/month-picker/MonthPickerCell.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateRangeTextInputFields.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateTextInputField.tsx
  packages/calendar/src/features/travel-calendar/hooks/UseTravelDateInput.ts
  packages/calendar/src/features/travel-calendar/hooks/UseTravelDateRangeInput.ts
Labels: enhancement, minor

#875 Add onOpened and onClosed props to Popover
  packages/tooltip/src/components/popover/Popover.stories.tsx
  packages/tooltip/src/components/popover/Popover.tsx
Labels: enhancement, minor

#876 Update horror story to work with new popover
  packages/grid/src/features/standard-table/stories/StandardTableHorror.stories.tsx
Labels: bug, patch, documentation

#877 Remove template folder from dependabot
  .github/dependabot.yml
  packages/calendar/package.json
  packages/core/package.json
  packages/elements/package.json
  packages/forms/package.json
  packages/grid/package.json
  packages/grid/src/features/standard-table/stories/StandardTableHorror.stories.tsx
  packages/modal/package.json
  packages/panels/package.json
  packages/tooltip/package.json
  yarn.lock
Labels: dependencies, patch

#885 Fix `generate-svg-icons` script
  packages/elements/src/icons/generated/ArrowIcons.ts
  packages/elements/src/icons/generated/BusinessIcons.ts
  packages/elements/src/icons/generated/CommonIcons.ts
  packages/elements/src/icons/generated/PassengerTypeIcons.ts
  packages/elements/src/icons/generated/UserIcons.ts
  scripts/generate-icons.cjs
Labels: bug, skip-release
