Repository StenaIT/stenajs-webui, pull requests merged in 2024-11, with the labels that each got.

#889 Add kraken xl icon
  packages/elements/src/icons/generated/XlIcons.ts
  scripts/icons/xl-icons/kraken-xl.svg
Labels: enhancement, patch

#890 Fix asymmetric padding in Tag when there is no label.
  packages/elements/src/components/ui/tag/Tag.module.css
  packages/elements/src/components/ui/tag/Tag.stories.tsx
  packages/elements/src/components/ui/tag/Tag.tsx
Labels: bug, patch

#897 Export DialogContext, in case someone creates custom modals in their apps
  packages/modal/src/index.ts
Labels: enhancement, patch

#899 Add ability to use useDialog hook without dialog element
  packages/modal/package.json
  packages/modal/src/declarative-modals/modal/Modal.stories.tsx
  packages/modal/src/declarative-modals/modal/Modal.tsx
  packages/modal/src/dialog/Dialog.mdx
  packages/modal/src/dialog/UseDialog.tsx
  packages/modal/src/dialog/alert/AlertDialog.stories.tsx
  packages/modal/src/dialog/modal/ModalDialog.stories.tsx
  yarn.lock
Labels: enhancement, minor

#900 Add icons for cabin windows and moon
  packages/elements/src/icons/generated/CommonIcons.ts
  scripts/icons/common-icons/moon-filled.svg
  scripts/icons/common-icons/window-excluded.svg
  scripts/icons/common-icons/window.svg
Labels: enhancement, patch

#910 Add some icons for cabin amenities.
  packages/elements/src/icons/generated/CommonIcons.ts
  scripts/icons/common-icons/bunk-bed.svg
  scripts/icons/common-icons/hairdryer.svg
  scripts/icons/common-icons/shower.svg
  scripts/icons/common-icons/smoking-no.svg
  scripts/icons/common-icons/soap.svg
  scripts/icons/common-icons/towels.svg
Labels: enhancement, minor

#911 Update Modal to look and feel like ModalDialog
  packages/modal/package.json
  packages/modal/src/declarative-modals/modal/Modal.module.css
  packages/modal/src/declarative-modals/modal/Modal.stories.tsx
  packages/modal/src/declarative-modals/modal/Modal.tsx
  packages/modal/src/dialog/modal/ModalDialog.stories.tsx
Labels: enhancement, minor

#912 Increase min-height since label increases size of tag
  packages/elements/src/components/ui/tag/Tag.module.css
Labels: bug, patch

#923 Added filled icon versions
  packages/elements/src/icons/generated/CommonIcons.ts
  scripts/icons/common-icons/bookmark-filled.svg
  scripts/icons/common-icons/question-circle-filled.svg
Labels: enhancement, minor

#924 Fix modal slide out animation bug
  packages/modal/src/dialog/UseDialog.tsx
  yarn.lock
Labels: bug, patch

#925 Fix bug where modal content was rerendered without props
  packages/modal/src/dialog/UseDialog.tsx
Labels: bug, patch

#927 - Add ModalContainer to InfoAlert.
  packages/modal/src/building-blocks/ModalContainer.tsx
  packages/modal/src/declarative-modals/modal/Modal.stories.tsx
  packages/modal/src/dialog/modal/ModalDialog.stories.tsx
  packages/modal/src/ready-made-modals/InfoAlert.tsx
Labels: patch, documentation

#930 Add support for more locales
  packages/calendar/src/components/calendar-types/travel-date-calendar/TravelDateCalendar.stories.tsx
  packages/calendar/src/components/calendar-types/travel-date-range-calendar/TravelDateRangeCalendar.stories.tsx
  packages/calendar/src/components/input-types/travel-date-input/TravelDateInput.stories.tsx
  packages/calendar/src/components/input-types/travel-date-range-input/TravelDateRangeInput.stories.tsx
  packages/calendar/src/features/localize-date-format/LocaleMapper.ts
  packages/modal/src/dialog/Dialog.mdx
Labels: enhancement, minor

#928 Add support for nested popovers
  packages/tooltip/src/components/popover/ControlledPopover.tsx
  packages/tooltip/src/components/popover/Popover.stories.tsx
  packages/tooltip/src/components/popover/Popover.tsx
Labels: enhancement, minor

#931 Add aria options to useDialog.
  packages/modal/src/dialog/UseDialog.tsx
Labels: enhancement, minor

#932 Add aria-label option to useDialog
  packages/modal/src/dialog/UseDialog.tsx
Labels: enhancement, patch
