Repository StenaIT/stenajs-webui, pull requests merged in 2024-01, with the labels that each got.

#700 Upgrade auto
  package.json
  yarn.lock
Labels: internal

#704 Fix bug in Box causing columnGap and rowGap to overwrite gap
  packages/core/src/components/layout/box/Box.tsx
  packages/core/src/utils/BooleanOrNumberToNumber.ts
Labels: bug, patch

#707 Add section on migrating from earlier modal version
  packages/modal/src/Modals.mdx
Labels: patch, documentation

#709 Fix rail menu hamburger button not visible when window is small
  packages/elements/src/components/ui/buttons/menu-button/IconMenuButton.tsx
  packages/panels/src/components/nav-bar/NavBar.stories.tsx
Labels: bug, patch

#710 Update padding, Chip and clear button in Select
  packages/elements/src/components/ui/buttons/common/BaseButton.tsx
  packages/elements/src/components/ui/chip/Chip.tsx
  packages/elements/src/components/ui/icon/CircledIcon.tsx
  packages/forms/src/components/ui/text-input/TextInput.module.css
  packages/modal/src/ready-made-modals/InfoAlert.stories.tsx
  packages/select/src/SelectTheme.ts
  packages/select/src/components/ui/ChipMultiSelect/ChipMultiSelect.tsx
  packages/select/src/components/ui/ChipMultiSelect/ChipRow.tsx
  packages/select/src/components/ui/MultiSelect.tsx
  packages/select/src/components/ui/OverflowingMultiSelect.tsx
  packages/select/src/util/StylesBuilder.ts
  packages/theme/src/styles/default-theme.css
Labels: enhancement, minor
