Repository StenaIT/stenajs-webui, pull requests merged in 2024-08, with the labels that each got.

#756 New rain icon
  packages/elements/src/icons/generated/CommonIcons.ts
  scripts/icons/common-icons/rain.svg
Labels: enhancement, patch

#757 Add size variants to travel calendar
  packages/calendar/src/components/calendar-types/travel-date-calendar/TravelDateCalendar.stories.tsx
  packages/calendar/src/components/calendar-types/travel-date-calendar/TravelDateCalendar.tsx
  packages/calendar/src/components/calendar-types/travel-date-range-calendar/TravelDateRangeCalendar.stories.tsx
  packages/calendar/src/components/calendar-types/travel-date-range-calendar/TravelDateRangeCalendar.tsx
  packages/calendar/src/components/input-types/travel-date-input/TravelDateInput.stories.tsx
  packages/calendar/src/components/input-types/travel-date-input/TravelDateInput.tsx
  packages/calendar/src/components/input-types/travel-date-range-input/TravelDateRangeInput.stories.tsx
  packages/calendar/src/components/input-types/travel-date-range-input/TravelDateRangeInput.tsx
  packages/calendar/src/features/month-picker/MonthPicker.tsx
  packages/calendar/src/features/month-picker/MonthPickerCell.tsx
  packages/calendar/src/features/travel-calendar/components/MonthHeader.tsx
  packages/calendar/src/features/travel-calendar/components/TravelCalendar.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateCell.module.css
  packages/calendar/src/features/travel-calendar/components/TravelDateCell.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateCellBackground.module.css
  packages/calendar/src/features/travel-calendar/components/TravelDateCellBackground.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateSingleTextInputField.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateTextInput.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateTextInputFields.tsx
Labels: enhancement, minor

#759 TravelCalendar has role, aria-selected and aria-multiselectable set properly
  packages/calendar/src/components/calendar-types/travel-date-calendar/TravelDateCalendar.tsx
  packages/calendar/src/components/calendar-types/travel-date-range-calendar/TravelDateRangeCalendar.tsx
  packages/calendar/src/components/input-types/travel-date-input/TravelDateInput.tsx
  packages/calendar/src/components/input-types/travel-date-range-input/TravelDateRangeInput.tsx
  packages/calendar/src/features/travel-calendar/components/TravelCalendar.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateCell.tsx
Labels: enhancement, patch

#758 New component: LabelHighlight
  packages/elements/src/components/ui/label/LabelHighlight.stories.tsx
  packages/elements/src/components/ui/label/LabelHighlight.tsx
  packages/elements/src/index.ts
Labels: enhancement, minor

#761 Add more building blocks for modals
  packages/modal/src/building-blocks/BuildingBlocks.mdx
  packages/modal/src/building-blocks/ModalActionButtons.stories.tsx
  packages/modal/src/building-blocks/ModalActionButtons.tsx
  packages/modal/src/building-blocks/ModalBody.tsx
  packages/modal/src/building-blocks/ModalContainer.tsx
  packages/modal/src/building-blocks/ModalFooter.module.css
  packages/modal/src/building-blocks/ModalFooter.stories.tsx
  packages/modal/src/building-blocks/ModalFooter.tsx
  packages/modal/src/dialog/modal/ModalDialog.module.css
  packages/modal/src/dialog/modal/ModalDialog.stories.tsx
  packages/modal/src/index.ts
  packages/modal/src/ready-made-modals/InfoAlert.tsx
  packages/theme/src/styles/default-theme.css
Labels: enhancement, minor

#762 Upgrade Storybook to 8.2.9 (new major)
  .storybook/main.ts
  package.json
  yarn.lock
Labels: dependencies, patch

#763 Some sizes updates to travel calendar.
  packages/calendar/src/features/travel-calendar/components/MonthHeader.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateCell.module.css
  packages/calendar/src/features/travel-calendar/components/TravelDateCellBackground.module.css
Labels: enhancement, patch

#764 Add size variant prop to RadioButtonBox
  packages/forms/src/components/ui/radio/RadioButtonBox.module.css
  packages/forms/src/components/ui/radio/RadioButtonBox.stories.tsx
  packages/forms/src/components/ui/radio/RadioButtonBox.tsx
Labels: enhancement, minor

#765 Fix width of inputs in travel calendar for size=large
  packages/calendar/src/features/travel-calendar/components/TravelDateTextInput.tsx
Labels: bug, patch

#766 Add screen reader support to several form inputs
  packages/forms/src/components/ui/checkbox/CheckboxWithLabel.tsx
  packages/forms/src/components/ui/radio/RadioButtonWithLabel.tsx
  packages/forms/src/components/ui/switch/SwitchWithLabel.tsx
Labels: enhancement, patch

#767 Add large heading size variant to ModalHeading
  packages/modal/src/building-blocks/ModalHeader.tsx
  packages/modal/src/building-blocks/ModalHeading.tsx
Labels: enhancement, patch

#768 Click outside to close modal now only reacts to onMouseDown.
  packages/modal/src/dialog/UseDialog.tsx
Labels: bug, patch

#771 Add test ids to travel calendar days
  packages/calendar/src/components/calendar-types/travel-date-calendar/TravelDateCalendar.stories.tsx
  packages/calendar/src/components/calendar-types/travel-date-calendar/TravelDateCalendar.tsx
  packages/calendar/src/components/calendar-types/travel-date-range-calendar/TravelDateRangeCalendar.stories.tsx
  packages/calendar/src/components/calendar-types/travel-date-range-calendar/TravelDateRangeCalendar.tsx
  packages/calendar/src/components/input-types/travel-date-input/TravelDateInput.stories.tsx
  packages/calendar/src/components/input-types/travel-date-input/TravelDateInput.tsx
  packages/calendar/src/components/input-types/travel-date-range-input/TravelDateRangeInput.stories.tsx
  packages/calendar/src/components/input-types/travel-date-range-input/TravelDateRangeInput.tsx
  packages/calendar/src/features/travel-calendar/components/TravelCalendar.tsx
  packages/calendar/src/features/travel-calendar/components/TravelDateCell.tsx
  packages/panels/src/components/sidebar-menu/items/RailMenuLink.tsx
  packages/panels/src/components/sidebar-menu/items/SidebarMenuLink.tsx
Labels: enhancement, patch

#772 New and updated icons
  packages/elements/src/icons/generated/CommonIcons.ts
  scripts/icons/common-icons/cafe.svg
  scripts/icons/common-icons/cog-alt.svg
  scripts/icons/common-icons/elevator.svg
  scripts/icons/common-icons/game-room.svg
  scripts/icons/common-icons/kids-room.svg
  scripts/icons/common-icons/play-room.svg
  scripts/icons/common-icons/reg-no.svg
  scripts/icons/common-icons/restrooms-gents.svg
  scripts/icons/common-icons/restrooms-ladies.svg
  scripts/icons/common-icons/sailing-crane.svg
  scripts/icons/common-icons/settings.svg
  scripts/icons/common-icons/spa.svg
Labels: enhancement, patch
