Repository StenaIT/stenajs-webui, pull requests merged in 2024-05, with the labels that each got.

#736 New and updated icons
  packages/elements/src/icons/generated/BusinessIcons.ts
  packages/elements/src/icons/generated/CommonIcons.ts
  scripts/icons/business-icons/business-agreement.svg
  scripts/icons/common-icons/basket.svg
  scripts/icons/common-icons/plus-small.svg
  scripts/icons/common-icons/sailing-trailer.svg
  scripts/icons/common-icons/share-alt.svg
  scripts/icons/common-icons/share.svg
Labels: enhancement, patch

#737 Add contentRight prop to RadioButtonBox
  eslint.config.js
  package.json
  packages/calendar/src/components/calendar-types/date-range-exclusion-calendar/DateRangeExclusionCalendar.stories.tsx
  packages/calendar/src/components/calendar-types/date-range-exclusion-calendar/DateRangeExclusionCalendar.tsx
  packages/calendar/src/components/calendar-types/date-range-exclusion-calendar/UseDateRangeExclusionSelection.ts
  packages/calendar/src/index.ts
  packages/core/src/components/layout/box/Box.tsx
  packages/filter/src/features/search-filter/section-factories/boolean-record/BooleanRecordChips.ts
  packages/forms/src/components/ui/radio/RadioButtonBox.stories.tsx
  packages/forms/src/components/ui/radio/RadioButtonBox.tsx
  packages/grid/src/features/standard-table/components/StandardTable.tsx
  packages/grid/src/features/standard-table/components/StandardTableCell.tsx
  packages/grid/src/features/standard-table/components/StandardTableContent.tsx
  packages/grid/src/features/standard-table/components/StandardTableRow.tsx
  packages/grid/src/features/standard-table/components/StandardTableRowList.tsx
  packages/grid/src/features/standard-table/features/sticky-columns/StickyColumnGroupValidator.ts
  packages/grid/src/features/standard-table/features/summary-row/components/StandardTableSummaryRow.tsx
  packages/grid/src/features/standard-table/features/summary-row/components/SummaryRowSwitcher.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement, minor

#738 Remove static width from RadioButtonBox contentRight
  packages/forms/src/components/ui/radio/RadioButtonBox.stories.tsx
  packages/forms/src/components/ui/radio/RadioButtonBox.tsx
Labels: bug, patch

#739 Fix bug where contentRight was incorrectly required
  packages/forms/src/components/ui/radio/RadioButtonBox.tsx
Labels: bug, patch

#740 RadioButtonBox icon was not right aligned
  package.json
  packages/forms/src/components/ui/radio/RadioButtonBox.tsx
  yarn.lock
Labels: bug, patch

#741 Add new icon empty-read-alt
  packages/elements/src/icons/generated/CommonIcons.ts
  scripts/icons/common-icons/empty-read-alt.svg
Labels: enhancement, patch

#742 Fix double icons on RadioButtonBox
  packages/forms/src/components/ui/radio/RadioButtonBox.tsx
Labels: bug
